general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 12

[window]
decorations = "None"
opacity = 0.80
blur = true
padding.x = 5
padding.y = 5

[colors]
transparent_background_colors = true

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[cursor.style]
shape = "Beam"
blinking = "Always"

[terminal.shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-s", "default"]
